name: 'Setup Kotlin'
description: 'Install the Kotlin compiler'
author: 'Florian Wilhelm'
branding:
  icon: 'code'
  color: 'orange'
inputs:
  version:
    required: true
    description: 'Version of the compiler to download, if not provided a default value is used.'
    default: '1.4.20'
  script:
    required: false
    description: 'Script to execute, if so desired. If not provided, no script is executed and Kotlin cli tools can be used in subsequent steps.'
runs:
  using: 'node12'
  main: 'dist/index.js'
