name: 'Setup Kotlin'
description: 'Install the Kotlin compiler'
author: 'Florian Wilhelm'
branding:
  icon: 'code'
  color: 'orange'
inputs:
  version:
    required: false
    description: 'Version of the compiler to download, defaults to latest'
  script:
    required: false
    description: 'Script to execute'
runs:
  using: 'node12'
  main: 'dist/index.js'
